FROM openjdk:23-jdk-oracle as builder

ARG COMPILED_DIR=/compiledir

WORKDIR ${COMPILED_DIR}

COPY src src
COPY .mvn .mvn
COPY pom.xml .
COPY mvnw .

RUN ./mvnw package -Dmaven.test.skip=true

ENV SERVER_PORT=8080
ENV SPRING_DATA_REDIS_HOST=localhost
ENV SPRING_DATA_REDIS_USERNAME=""
ENV SPRING_DATA_REDIS_PASSWORD=""
ENV SPRING_DATA_REDIS_PORT=6379
ENV SPRING_DATA_REDIS_DATABASE=0
ENV POKEMON_API_URL=""
ENV POKEMON_API_KEY=""

EXPOSE ${SERVER_PORT}

#second stage
FROM openjdk:23-jdk-oracle

ARG WORK_DIR=/app

WORKDIR ${WORK_DIR}

COPY --from=builder /compiledir/target/Pokemon_TCG_TEST-0.0.1-SNAPSHOT.jar Pokemon_TCG_TEST-2.0.jar

ENV SERVER_PORT=8080
ENV SPRING_DATA_REDIS_HOST=localhost
ENV SPRING_DATA_REDIS_USERNAME=""
ENV SPRING_DATA_REDIS_PASSWORD=""
ENV SPRING_DATA_REDIS_PORT=6379
ENV SPRING_DATA_REDIS_DATABASE=0
ENV POKEMON_API_URL=""
ENV POKEMON_API_KEY=""

EXPOSE ${SERVER_PORT}

ENTRYPOINT java -jar Pokemon_TCG_TEST-2.0.jar


